// types

export const GET_CHARACTERS = 'GET_CHARACTERS';
export const CHARACTERS_RECEIVED = 'CHARACTERS_RECEIVED';
export const CHARACTERS_REQUEST_FAILED = 'CHARACTERS_REQUEST_FAILED';
export const SET_CHARACTER = 'SET_CHARACTER';
